name: CICD

on:
    push
jobs:
    build:
       runs-on: ubuntu-latest
       steps:
         - name: Uptime
           run: uptime
         - name: number of processor
           run: nproc 
           
    test:
         needs: [build]
         runs-on: ubuntu-latest
         steps:
            - name: Hello
              run: echo "Hello World"