name: CICD

on:
    push
jobs:
    build:
       runs-on: ubuntu-latest
       steps:
         - name: Check out code
           uses: actions/checkout@v4
         - name: Build Image
           run:  docker build -t dkflora/appfolio .
         - name: List Images
           run:  docker images
           